# -*- coding: utf-8 -*-
"""Movie Recommendation system with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eg5PaNAnu-BIAPMShoaFcbxP5WdvQLv
"""

import pandas as pd

df = pd.read_csv('movie_dataset.csv')

(df.iloc[14])['tagline']
df.head()

df2 = df[['keywords','cast','genres','director']]
df2.fillna('', inplace=True)

def combine_feature(a,b,c,d):
  return a+" "+b+" "+c+" "+d

df2['combined_feature']= combine_feature(df2['keywords'],df2['cast'],df2['genres'],df2['director'])

df2.head()
len(df2)

from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer()
X = vector.fit_transform(df2['combined_feature'])

from sklearn.metrics.pairwise import cosine_similarity

Y = cosine_similarity(X)

def index_from_title(title):
  return df.index[df['original_title']==title].tolist()

def title_from_index(number):
  return df.iloc[number]['title']

title_from_index(94)

